apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dj-ascale
  namespace: mindbox-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deploy-dj
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 20
