apiVersion: v1
kind: Service
metadata:
  name: dj-web-svc
  namespace: mindbox-ns
spec:
  selector:
    name: md-pod
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30009
